language: python
sudo: required
dist: xenial
services: postgresql
before_script:
- psql -f server/setup/internal/setup_database.sql -U postgres
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r server/setup/internal/server-pip-requirements.txt
- pip install -r client/setup/internal/minimum-test-pip-requirements.txt
script:
- "./test.sh"
before_deploy:
- cd client/
deploy:
  provider: pypi
  user: "len0rd"
  password:
    secure: "Uj0x/zlPFzppX4f+h4IGUMjvKWQVQqK+eZBrsuT3VJqetUAYfUn5+ZKe+xacBJb0d+yLH/gQJkF8kLqlZt153/YakCkZ9daJYCz9X1lUvm9GGGUvTZohLJz3fvbTOV68Qpuu9j7yPVeakMlnATkymkGj84XmfXQdL2AeoT5+lqn9N7KVSDu2tACynYUxC7SBMdBEc4PZOVwm/o3Hf+rTRqHZMLkl1RiHrrVxTiiSwlpivzO8xeLagoXPVsJ7Zujj/HqfF4PVHXReKU0FTE7fz+Qzw8IISNkpmJFdUoUp0ekcugQqof5HsAlZ+xrpjv/83xGNXdtzvF3obE913NKDvKdXwsQbRDYic649z77Ez79Cy7qme40zA5wb3OoOFVc/iqGGisTCjatoLDF6JiP5s9NbBRF413jEo5wyhBiX28FR+kXrtPpODWaPrVTqzY2jYadzUkOFHfUZde/rassK+lxR5E6mvJIqj1afkM1P9GIp+Wk4GoFJpIlhCVFLgC/dMurwnVST9h/gYlc7xoxWuHeoZPJgAe6ipNa0t+c2wpPFEheaYe/dn5+BUmJsmiuzfbPQEDI8OpLbgtL5n9JKMOHakTZ+utGEe5o/zVNGdjV+++ooiSSJCykagozmPJYWq/F+V2dU0MJt6lVQu+UpQlk+gIeaf/SdkC7WMPE/0z4="
  on:
    tags: true
  distributions: "bdist_wheel sdist"
  skip_existing: true
