language: python
sudo: required
dist: xenial
services: postgresql
before_script:
- psql -f server/setup/internal/setup_database.sql -U postgres
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r server/setup/internal/server-pip-requirements.txt
- pip install -r client/setup/internal/minimum-test-pip-requirements.txt
script:
- "./test.sh"
before_deploy:
- cd client/
deploy:
  provider: pypi
  user: "len0rd"
  password:
    secure: "diySio+ynR1uogdya6yts29Mm+oUGy0o8paIUjKr4qESMdMqVZ3mOrJP4kAL2/rmnR/Iv9wNRz4TYEdT6veH5kZlcZeGkaFROyiGMv1zpeqh3aHTkIpriz9a7/sq4PRnOfNDEWVNsgn9Op+DIbtTKrRp7Qg23AC3lyS7c/e/Aln0NS/b2McaLuMTIziE59bLrpY96+Jr4IBsnMGQSUQ2wUhB6cHoE6RTFKwVeZDxdZ8EFLf9AYoi8fH7WtTM7li9kDpQhkcjuIgDQTC5HIiG1k4wPs5PSzXwefGomKRoncIvzQi2W/bVOA59WRM2sHrZUslwwNguK9CwacKhkh4Bmdoeam3XlUahR8V0+fVLweLvS1KcPNxjBVGOMHCY+kREXw2J28OLKTLcIFZrwUouUyCUK2gB6KuRxg6K999irZcPdw1TJr/m57ciZfODrDrYeFyyidFclXmB+fa8hSe7LF37ZPeh1cqrISQTCdABOdooU3Qdg3YJaBkhVQV9hbaXJnNblyn2BRo6JiU8JkGMds2ePQhuF36dL33ue1GSt5CDRN8M4JjDv+wn5aCmDYKyW5wKEXLrjn7X/SFhh7StLk+TOArq0DhNKSTYww65oFO2i8AsHKD7yjL4ZwWLM4Mdf3XeLLIEo4fsWqVRem8qynG7Y6wTiTmf7fyr4P8vcm4="
  on:
    tags: true
  distributions: "bdist_wheel sdist"
  skip_existing: true
