name: byu-auvsi-server
version: 0.1
summary: Imaging server for BYU AUVSI team
description: |
  Runs all server-side code for Byu's auvsi imaging platform.


grade: devel
confinement: devmode

parts:
  imaging-server-base:
    plugin: python
    python-version: python3.7
    source: src/
    source-type: git
    requirements: setup/pip-requirements.txt

  imaging-ingest:
    source: https://github.com/BYU-AUVSI/imaging.git
    source-branch: master
    plugin: catkin
    rosdistro: kinetic
    source-space: server/
    catkin-packages: [imaging_ros_ingester]

  ros-tutorials:
    source: https://github.com/ros/ros_tutorials.git
    source-branch: kinetic-devel
    plugin: catkin
    rosdistro: kinetic
    source-space: roscpp_tutorials/
    catkin-packages: [roscpp_tutorials]


apps:
  run:
    command: roslaunch roscpp_tutorials talker_listener.launch