import json, os, shutil
from config import defaultSubmittedImgDir

class AuvsiOdlcDao():

    # A list of keys to exclude in the output .json file generated by the DAO
    KEYS_TO_EXCLUDE = ['id', 'target', 'crop_id', 'crop_path', 'submitted']

    def addTarget(self, targetClassification, imgPath, manual=True):
        """ 
        Adds the given target classification to the ODLC backup folder.

        This folder stores all the targets that we attempt to submit to the judges
        in the ODLC target format as described in the rules PDF for AUVSI.
        The final structure looks something like this:

        images
          |--1546372042
              |--submitted
                   |--manual
                       |--1.json
                       |--1.jpg
                       |--2.json
                       |--2.jpg
                    |--autonomous
                       |--1.json
                       |--1.jpg
                       |--3.json
                       |--3.jpg
        """
        # get the path we'll be saving to:
        baseSubmittedPath = defaultSubmittedImgDir()
        if manual:
            baseSubmittedPath += 'manual/'
        else:
            baseSubmittedPath += 'autonomous/'
        
        if not os.path.exists(baseSubmittedPath):
            os.makedirs(baseSubmittedPath)
        
        outDict = targetClassification.toDict(exclude=self.KEYS_TO_EXCLUDE)
        jsonFileOut = baseSubmittedPath + str(targetClassification.target) + '.json'

        extension = imgPath.rsplit('.', 1)[1].lower()
        fileName  = imgPath.rsplit('/', 1)[1]
        newFileName = str(targetClassification.target) + extension

        # write target info to dictionary
        with open(jsonFileOut, 'w') as f:
            json.dump(outDict, f)

        # copy over
        shutil.copy(imgPath, baseSubmittedPath)
        
        # rename file
        dst_file = os.path.join(baseSubmittedPath, fileName)
        new_dst_file_name = os.path.join(baseSubmittedPath, newFileName)
        os.rename(dst_file, new_dst_file_name)

        return None