[epydoc] # Epydoc section marker (required by ConfigParser)

# Information about the project.
name: AUVSI Imaging Server

# The list of modules to document.  Modules can be named using
# dotted names, module filenames, or package directory names.
# This option may be repeated.
modules: ../src/dao/ ../src/ros_handler.py

# Write html output to the directory "apidocs"
output: pdf
target: ../docs/pdf/